logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.0.102:8762/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://192.168.0.102:8001/auth/users/current

spring:
  activemq:
    broker-url: tcp://192.168.0.102:61616
    user: admin
    password: admin

db:
  connection:
    url: jdbc:h2:tcp://192.168.0.102:9123/~/test
    port: 9123
    username: sa
    password:
