logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8001/auth/users/current

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin